---
- name: Change primary Ansible user password
  hosts: windows-server-01
  gather_facts: no

  collections:
    - ansible.windows

  # Connect using the secondary account credentials defined in inventory vars
  vars:
    ansible_user: "{{ ansible_secondary_username }}" # Connect using the secondary account

  tasks:
    - name: Load secondary vault for connection
      include_vars:
        file: ../.secrets/secondary_vault.yml
        name: secondary_cred

    - name: Set connection password for secondary service account
      set_fact:
        ansible_password: "{{ secondary_cred.vault_windows_password }}"

    - name: Ping the target host with secondary account (optional, for verification)
      ansible.windows.win_ping:

    - name: Load new primary password from vault
      include_vars:
        file: ../.secrets/new_primary_vault.yml # This vault must contain the new password for the primary user
        name: new_primary_cred

    - name: Change password for the primary Ansible user
      ansible.windows.win_user:
        name: "{{ ansible_primary_username }}" # Dynamic primary username from inventory
        password: "{{ new_primary_cred.vault_windows_password }}" # Uses the password from new_primary_vault.yml
        state: present
        update_password: always # Essential to force a password change for an existing user
        password_never_expires: yes # Keep this if it's a service account
      become: yes
      become_method: runas
      become_user: "{{ ansible_user }}" # This will resolve to ansible_secondary_username